### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by agjohnson** [humitos/readthedocs-client#1]
Just a note for later, I thought this summarized the necessary changes for a test suite fairly well: https://github.com/readthedocs/ethical-ad-client/pull/150

The test suite here will be similar, we'll have DOM tests and need to test the output from Webpack

**Comment by humitos** [comment]
I have a lot of questions here regarding how to start:

* How do we write a test case?
* How do we execute the test case?
* Where those tests are run? Do I have access to the DOM to compare expected with obtained? How?
* What kind of tests we want to write?
* How strict we have to be?
* How do we mock the API endpoint that gives us the JSON file?
* etc

**Comment by agjohnson** [comment]
I would just start with something small, to verify basic functions of the library here. Nothing major like DOM testing.

The link above has a test case:
https://github.com/readthedocs/ethical-ad-client/pull/150/files#diff-df185567239fc7a16574de1fb33242726a3f34d5b96e265b43d8786a50d1ebe8

This is using Jest, testing in Node is done with the `npm test` command.

**Comment by humitos** [comment]
Added them in d3472c417b333b1698b77135f3f8cce4e881ba81
