### ISSUE TITLE
Add static files for hosting to this repo

### ISSUE THREAD

**Issue by agjohnson** [humitos/readthedocs-client#7]
On the doc-diff repo, there is a `public/` directory. This has a functional test
of the library for testing/QA, and tests the whole library at once. I found it
extremely helpful in isolating testing, and avoids a testing scenario where you
need to build the client and inject it back through the application or documentation
build in order to test.

I did a quick test here, I can put up a draft PR to illustrate what I did. It will need a bunch of work still though. I just did the minimal version of this.

**Comment by humitos** [comment]
I'm not sure to understand what you are suggesting here. Opening those files under `public/` with Firefox does nothing 🤷🏼 . I may need an example or more explanation about this.

**Comment by agjohnson** [comment]
`public/` is the path served by the dev server at `/`. If you put an index file in `/public`, it will be the page that shows when you bring up the dev server.

**Comment by humitos** [comment]
Gotcha! I got the doc-diff working locally using the `public/` files. I will try to copy the pattern of it with an integration example.

**Comment by humitos** [comment]
The initial work is done at 55bf10d. You can

```bash
npm run dev
```

and open http://localhost:8081/sphinx/ to see all the integrations working.

My idea is to have several examples in the `public/` folder that are built from `examples/`. For now, I just added Sphinx as a first test, but we can add other doctools later.

Feel free to close this issue is this is what you was expecting.

**Comment by agjohnson** [comment]
Yup, that's perfect! Multiple test scenarios for different tools is a great idea :100: 

Only thing I noticed in that commit is this:
https://github.com/humitos/readthedocs-client/commit/55bf10d30180c5d105bd270fc6e38232db7e8b2a#diff-1fb26bc12ac780c7ad7325730ed09fc4c2c3d757c276c3dacc44bfe20faf166fR17

The `</head>` is not closed. It's safe to close this up otherwise though.

**Comment by humitos** [comment]
Ups, that's a typo :)

Fixed in 80a3ecf

**Comment by humitos** [comment]
Thanks for reviewing all this work, BTW! 🙏🏼
